### ISSUE TITLE
WiFi handshake failure

### ISSUE THREAD

**Issue by raivol** [ms-iot/remote-wiring#101]
Hi,
I'm using a Arduino/Genino MKR1000 board with the Windows Remote Arduino Experience App.
After uploading the StandardFirmata sketch to the board, Windows Remote Arduino Experience
connects to the board without any problems, both USB and Bluetooth connetctions work fine.
Now when running the StandardFirmataWiFi sketch on the board, Windows Remote Arduino Experience fails to
connect with the following Error Message :

"Connection attempt failed. A device connection was established, but the device failed handshaking procedures.
Verifiy that your device is configured with StandardFirmata. Message : Catastrophic Failure Pin configuration
not received."

I'm using version 1.6.9 of the Arduino ide.
Firmata Library v 2.5.2
WiFi101 v 0.9.1

(Enabling the Serial Monitor when running StandardFirmataWiFi shows no problems, an ip-address is obtained
so the board is connected to the network)

Any ideas what the problem might be ?

**Comment by IoTGirl** [comment]
Hi Raivol,
Unfortunately we do not have the hardware you are using. As [documented](https://developer.microsoft.com/en-us/windows/iot/docs/wra) this is tested with an Arduino Uno and in the case of Wifi, an Arduino WiFi Shield.  Our only guidance would be to investigate how your setup differs from the tested setup to see where the issue may lie.
Sincerely,
IoTGirl
