### ISSUE TITLE
Code not working in Visual Basic 2015

### ISSUE THREAD

**Issue by TonyScarpelli** [ms-iot/remote-wiring#105]
I am trying to get Windows-Remote-Arduino working in a Visual Basic 2015 Universal application.

I got it to work all right with this C# code:
  connection.ConnectionEstablished += OnConnectionEstablished;
  connection.begin(115200, SerialConfig.SERIAL_8N1);

In VB, when I type in  connection.  the options that appear are: available, begin, connectionReady, etc.

None of them seem to work.

I am trying to figure out the code to make this work.
What option is similar to ConnectionEstablished?

Thanks.

**Comment by sadersa** [comment]
try
connection.DeviceConnectionFailed+= OnDeviceConnectionFailed;

**Comment by IoTGirl** [comment]
No response - closing as stale.
