### ISSUE TITLE
Feature request: Implement ConfigurableFirmata

### ISSUE THREAD

**Issue by jsiegmund** [ms-iot/remote-wiring#106]
I'd like to request the implementation of ConfigurableFirmata which in turn allows us to have a more extendable way of connecting with firmata devices. In my particular use case I want to be able to query OneWire sensors over firmata. ConfigurableFirmata has a OneWire module which can be used to do this. 

Would be awesome when the remote-wiring library would include support for ConfigurableFirmata. I made a small attempt at implementing but I'm afraid my C++ knowledge is way too rusty for me to do so effectively. There are existing libraries with support for ConfigurableFirmata available in JavaScript and Ruby, so there's sample code to start from. 

See https://github.com/firmata/ConfigurableFirmata

**Comment by peterkorolev** [comment]
+1

**Comment by saraclay** [comment]
If this issue is still relevant, please file this at: https://github.com/MicrosoftDocs/windows-iotcore-docs
