### ISSUE TITLE
Added DF Robot BLE Serial 

### ISSUE THREAD

**Issue by matjd** [ms-iot/remote-wiring#107]
I'm trying to use this but no luck.  The DfRobot forum tells me that the Bluno will only talk to their own gear and app.. but I guess that the inclusion of DfRBLE here suggests that it can be done.

Do you have an example please ?  I can't see the Bluno through the sample code or through the Remote Arduino Experience App :(

**Comment by IoTGirl** [comment]
Closing as duplicate of [https://social.msdn.microsoft.com/Forums/en-US/5fe6733a-d99e-45cc-b5ae-debc2ab212ea/windows-remote-arduino-and-dfrobot-bluno-nano?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/en-US/5fe6733a-d99e-45cc-b5ae-debc2ab212ea/windows-remote-arduino-and-dfrobot-bluno-nano?forum=WindowsIoT)
