### ISSUE TITLE
CAPABILITY_QUERY is sent many times by BleSerial

### ISSUE THREAD

**Issue by matsujirushi** [ms-iot/remote-wiring#109]
When using BleSerial, CAPABIRITY_QUERY is sent many times on connection.
It takes about 300 to 400 milliseconds for BLE to be connected from pairing, but the retransmission interval is shorter than that.

`
                const int MAX_ATTEMPTS = 30;
		const int MAX_DELAY_LOOP = 5;
		const int INIT_DELAY_MS = 10;
`

**Comment by IoTGirl** [comment]
Hi Kara,
Could you review this issue?
Sincere thanks,
IoTGirl

**Comment by KaraOttewell** [comment]
No longer working in this area

**Comment by saraclay** [comment]
If this issue is still relevant, please file this at: https://github.com/MicrosoftDocs/windows-iotcore-docs
