### ISSUE TITLE
Can i use this library in WPF application windows 10 ?

### ISSUE THREAD

**Issue by sadersa** [ms-iot/remote-wiring#110]
Hi all
Tell me please.
Can i use this library in WPF application windows 10 ?
Thanks

**Comment by IoTGirl** [comment]
Hi Sadersa,
The [documentation](https://developer.microsoft.com/en-us/windows/iot/docs/wra) states this is open source so you may use it in your projects. There is no specific support for WPF.
Sincerely,
IoTGirl
