### ISSUE TITLE
CPU core is fully utilized after calling Firmate.begin()

### ISSUE THREAD

**Issue by Qowy** [ms-iot/remote-wiring#114]
Due to the constantly polling nature of the inputThread() listening for messages from the serial connection one CPU core is fully utilized during the entire runtime of the Firmata class.

https://github.com/ms-iot/remote-wiring/pull/113 proposes a simple optional fix that allows one to specifiy a polling intervall during constuction of the UwpFirmata class.

https://github.com/ms-iot/remote-wiring/pull/115 Is a nicer solution but requires a change to Microsoft.Maker.Serial.ISerial (https://github.com/ms-iot/serial-wiring/pull/20) that introduces (in order to not change existing functionality) a readBlocking() method that puts the current thread to sleep until LoadAsync() is complete

I also experimented with a solution that exposes ISerial::available() and read() (or would introduce availableAsync() etc.) as IAsyncOperation<uint16_t>,
however this would require even more changes to the ISerial interface and is complex to do with the create_task().then() approach.

co_await might make it easy, but I am unsure if using `#include <experimental\resumable>` is allowed in such a low level library

**Comment by saraclay** [comment]
If this issue is still relevant, please file this at: https://github.com/MicrosoftDocs/windows-iotcore-docs
