### ISSUE TITLE
Xamarin Support

### ISSUE THREAD

**Issue by dapug** [ms-iot/remote-wiring#117]
Remote wiring support in a Xamarin.Forms project which includes UWP would be extremely useful.

**Comment by IoTGirl** [comment]
Hi @dapug,
I asked a member of the Xamarin team to take a look at your request.  He stated the he was not familiar with Remote Arduino specifically but you could probably create a Xamarin.Forms port as Xamarin does already have quite a bit of Bluetooth LE code.
Sincerely,
IoTGirl
