### ISSUE TITLE
Analog Write Doesn't work in v1.4

### ISSUE THREAD

**Issue by ankur198** [ms-iot/remote-wiring#126]
I don't understand the working but I tried in my project that when I used remote-arduino v1.4 from nuGet I wasn't able to perform analogWrite operations, but after downgrading to v1.2 (without any other code chamges), everything worked perfectly.

**Comment by IoTGirl** [comment]
Hi @ankur198,
Can you tell us more about your setup? If IU were to try and see your issue what devices, software and hardware would I need and what steps would I have to take to see this issue. 
NOTE: Saying to use the steps in GITHUB is not enough. Please clarify which step and how the failure appears.
Sincerely,
IoTGirl

**Comment by ankur198** [comment]
Actually that was my fault, I tried to analog write on a pin where it was not possible. Version 1.4 didn't sent a message to arduino at all, however version 1.2 did sent it.
