### ISSUE TITLE
[Firmata] Smart delay when `0xFFFF` is received from `read()`

### ISSUE THREAD

**Issue by zfields** [ms-iot/remote-wiring#13]
Reduce the polling frequency on the `processInput()` reader thread when no data is available to read; perhaps using a back-off algorithm.

In a simple example, have no delay if the last read was successful, but have an incremental delay as each successive read fails (i.e 1ms, 2ms, 4ms, 8ms, 16ms, 32ms, 64ms, 128ms, 128ms, 128ms, etc.).

A slightly more sophisticated example would be to keep a last successful read timestamp, then use a logarithmic function to generate a "time-to-delay" curve based on the time passed since last successful read.

**Comment by saraclay** [comment]
If this issue is still relevant, please file this at: https://github.com/MicrosoftDocs/windows-iotcore-docs
