### ISSUE TITLE
DHT11 + Arduino UNO + Raspberry pi 3 + Win10iotCore

### ISSUE THREAD

**Issue by edgardmi** [ms-iot/remote-wiring#130]
Hello,
I need to read with C# UWP App, a DHT11/DHT22 sensor to get temperature and the arduino is conected to an Arduino UNO.
Can I use "digitalRead" at sensor PIN and converte the values using C# library 
'sensors.dht'? Or I need to change the FirmataStandard sketch to include dht library and receive the values "cleaned"?

Thanks very much!

**Comment by saraclay** [comment]
If this issue is still relevant, please file this at: https://github.com/MicrosoftDocs/windows-iotcore-docs
