### ISSUE TITLE
IS this working forVIsual Studio

### ISSUE THREAD

**Issue by jecalderon** [ms-iot/remote-wiring#137]
I clone this REPO and opened in Visual Studio 2017.  Built fail and returned several errors.  Do you have a suggestion?  I interested on the FIRMATA client for a WIndows 10  in C++ VIsual studio compiler.

**Comment by saraclay** [comment]
Hello,

If this is still an issue for you, could you please repost this in our MSDN forums? We have staff there that are monitoring the forums and will be able to help you.

MSDN forums: https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT
