### ISSUE TITLE
[Serial] Improve code clarity by refactoring to more meaningful names in private members

### ISSUE THREAD

**Issue by zfields** [ms-iot/remote-wiring#20]
Refactor `connectAsync()` to `connectToDeviceAsync()` (more literal)
Refactor `_deviceIdentifier` to `_deviceName` (more common usage)

**Comment by turkycat** [comment]
this issue resolved in commits 7e2ba12cea2d663798f7181958e6ebca7022a6de and 99c3032eeafa86d2f51612638241b9f996c92a33
