### ISSUE TITLE
[Serial] Use MSDN markup to provide "tooltip" information

### ISSUE THREAD

**Issue by zfields** [ms-iot/remote-wiring#22]
Add `<summary>`, `<params>`, `<details>` comment sections before each method, so the user will get information about the methods functionality when hovering over the signature.

**Comment by turkycat** [comment]
This is complete, but I do not get the method summary popups when using Windows Remote Arduino in other projects, is there a missing step?

**Comment by turkycat** [comment]
@zafields this is complete, there are summary tags above every function
