### ISSUE TITLE
Only works with 'OldStandardFirmata'

### ISSUE THREAD

**Issue by frogger3d** [ms-iot/remote-wiring#25]
It seems the library only works when you flash an Arduino with the 'OldStandardFirmata'
sketch. When you flash the StandardFirmata it connects fine, but nothing happens. It would be wise to add this to the documentation or better yet support the new standard sketch.

I haven't dug deeper, but this was using the https://github.com/ms-iot/windows-remote-arduino-samples project with an Arduino Uno with a BlueSmirf Silver connected to a Surface Pro 3 running Win 8.1 pro.

**Comment by frogger3d** [comment]
Oops, just a case of different defaults.. My bluetooth device was set to 115200 baud, which is the default for OldStandardFirmata. The StandardFirmata is defaulted to 57600 baud, but when changed to 115200 it worked just fine. The code comment in RemoteBlinky threw me off (baud rate does matter, but only on the Arduino side):

            //these parameters don't matter for bluetooth
            bluetooth.begin(115200, SerialConfig.SERIAL_8N1);

**Comment by turkycat** [comment]
I'll update that comment for clarity, thanks for following up!
