### ISSUE TITLE
[RemoteWiring] Pinmode uses firmata constructs instead of wiring

### ISSUE THREAD

**Issue by connerbrooks** [ms-iot/remote-wiring#28]

**Comment by zfields** [comment]
Should be `pinMode(A1, OUTPUT);`, not `pinMode(A1, PWM);`

**Comment by zfields** [comment]
@turkycat Were you able to resolve this by providing multiple signatures for `pinMode()`?

**Comment by turkycat** [comment]
I believe this issue represents the fact that pinMode accepts an enum type which includes ANALOG, PWM, SERVO, IGNORED, etc rather than just INPUT and OUTPUT. As it currently exists, these constructs are necessary to attach servos, differentiate between digital and analog input, etc

**Comment by zfields** [comment]
I don't think the ability to use additional (more descriptive) pinmodes is the problem. I believe the issue was raised because Conner was not able to use `pinmode()` in the way it would be used with Arduino, therefore the library was unintuitive.

**Comment by turkycat** [comment]
If the new overloads for pinMode accepting strings like "A0" solves this problem, then that's great, and we can close the issue. I assumed the "construct" in question was the extra (firmata-defined) "modes"

**Comment by zfields** [comment]
You have a better grasp of the new library functionality than I do, and I was with Conner when he posted the issue. Let's whiteboard it to verify, but I think this solution may be sufficient.

------ I'll update the issue and respond below with the result of our meeting -------

**Comment by turkycat** [comment]
@zafields ping
