### ISSUE TITLE
[Firmata] `void endSysex(void)` signature mismatch

### ISSUE THREAD

**Issue by zfields** [ms-iot/remote-wiring#31]

**Comment by turkycat** [comment]
I am not sure how these mismatch. The signature is the exact same between both "raw" Firmata and UwpFirmata. Can you clarify?

**Comment by zfields** [comment]
UWPFirmata.h: line 242
`bool endSysex(void);`

**Comment by turkycat** [comment]
@zfields Please close this issue as well, it is out of date!
