### ISSUE TITLE
AnalogPinUpdatedCallback uses byte argument instead of string

### ISSUE THREAD

**Issue by VannosG** [ms-iot/remote-wiring#55]
Other methods such as `analogRead()` accept a string argument, such as "A0", yet the `AnalogPinUpdatedCallback` delegate has a `byte` argument. The contracts for all analog methods should be aligned and always work with the string argument.

**Comment by turkycat** [comment]
The byte parameter is a remnant from before the string functionality was possible (due to difficulty translating it into the correct pin number). I do not disagree with your suggestion! We will take it into consideration and potentially make the change. Thanks!
