### ISSUE TITLE
example of digitl pin updated

### ISSUE THREAD

**Issue by abhishekdaya** [ms-iot/remote-wiring#79]
Hi... Can anyone please show an example of digitalpinupdated and analogpinupdated code.... Tnks....

**Comment by abhishekdaya** [comment]
I just have the folowing queries...
1) Digital Update only gives the state when changed from Low to High...
2) The above is happening only once.... I.E. The second time i toggle a switch i dont get any feedback.....

**Comment by abhishekdaya** [comment]
I am using arduino uno and the commincation is via bluetooth... I am using the module HC-05... @11520 BR...

**Comment by turkycat** [comment]
Hey @abhishekdaya , we've got another report of an issue with HC-06 devices. It may be a problem with similar devices as well. I've got an HC-06 on order and will update the issues once I have been able to test the device

**Comment by zfields** [comment]
@abhishekdaya Can you provide a pointer to your code?

**Comment by IoTGirl** [comment]
Closing stale - No response in more than a year.
