### ISSUE TITLE
Can not NuGet on Windows 8.1

### ISSUE THREAD

**Issue by TAMHAN** [ms-iot/remote-wiring#94]
Hello,
working on Windows 8.1 and a Windows 8.1 universal app, deploying the NuGet Package yields the error:
Attempting to gather dependencies information for package 'Windows-Remote-Arduino.1.3.0' with respect to project 'SUSArduino1\SUSArduino1.Windows', targeting 'Windows,Version=v8.1'
Attempting to resolve dependencies for package 'Windows-Remote-Arduino.1.3.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Windows-Remote-Arduino.1.3.0'
Resolved actions to install package 'Windows-Remote-Arduino.1.3.0'
Install failed. Rolling back...
Package 'Windows-Remote-Arduino.1.3.0 : ' does not exist in project 'SUSArduino1.Windows'
Package 'Windows-Remote-Arduino.1.3.0 : ' does not exist in folder 'C:\Users\TAMHAN\Desktop\SUSArduinoWin\SUSArduino1\packages'
Could not install package 'Windows-Remote-Arduino 1.3.0'. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========

Please remedy!

With compliments
Tam HANNA

**Comment by zfields** [comment]
This library was initially developed for Windows 8.1, however with the move to Windows 10 the Windows 8.1 version of the library was deprecated. We left the projects and solution behind for makers to work with. If you clone the repositories, then you can add the projects directly into your solution. That is how we used to hand-stitch them originally. Cheers!
